server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-respuestas
  datasource:
    url: jdbc:mysql://localhost:3307/db_microservicios_examenes
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: America/Mexico_City
    locale: es_MX

  jpa:
    generate-ddl: true

  logging:
    level:
      org:
        hibernate:
          SQL: debug

